packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@scarf/scarf"
  - esbuild
  - prisma
allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": true
  esbuild: true
  prisma: true
