export enum ValidationErrorCode {
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  WALL_NOT_FOUND = "WALL_NOT_FOUND",
  LEVEL_NOT_FOUND = "LEVEL_NOT_FOUND",
  VIEWPOINT_NOT_FOUND = "VIEWPOINT_NOT_FOUND",
  BASE_IMAGE_NOT_FOUND = "BASE_IMAGE_NOT_FOUND",
  DESIGN_BRIEF_NOT_FOUND = "DESIGN_BRIEF_NOT_FOUND",
  RENDER_REQUEST_NOT_FOUND = "RENDER_REQUEST_NOT_FOUND"
}

