export enum MigrationErrorCode {
  MISSING_SCHEMA_VERSION = "MISSING_SCHEMA_VERSION",
  INVALID_SCHEMA_VERSION = "INVALID_SCHEMA_VERSION",
  UNSUPPORTED_PROJECT_SCHEMA_VERSION = "UNSUPPORTED_PROJECT_SCHEMA_VERSION",
  INVALID_LEGACY_SHAPE = "INVALID_LEGACY_SHAPE",
  LEGACY_ROOM_BOUNDARY_MIGRATION_FAILED = "LEGACY_ROOM_BOUNDARY_MIGRATION_FAILED",
  CANONICAL_VALIDATION_FAILED = "CANONICAL_VALIDATION_FAILED"
}

export enum LegacyRoomBoundaryMigrationFailureReason {
  MISSING_WALL = "MISSING_WALL",
  CROSS_LEVEL_WALL = "CROSS_LEVEL_WALL",
  DUPLICATE_WALL_REFERENCE = "DUPLICATE_WALL_REFERENCE",
  DEGENERATE_WALL = "DEGENERATE_WALL",
  OPEN_LOOP = "OPEN_LOOP",
  DISCONNECTED_LOOP = "DISCONNECTED_LOOP",
  BRANCHING_GRAPH = "BRANCHING_GRAPH",
  MULTIPLE_VALID_LOOPS = "MULTIPLE_VALID_LOOPS",
  DEGENERATE_POLYGON = "DEGENERATE_POLYGON",
  SELF_INTERSECTING_LOOP = "SELF_INTERSECTING_LOOP",
  PARTIAL_BOUNDARY_OVERLAP = "PARTIAL_BOUNDARY_OVERLAP",
  DUPLICATE_WALL_GEOMETRY = "DUPLICATE_WALL_GEOMETRY",
  NON_MANIFOLD_REFERENCE = "NON_MANIFOLD_REFERENCE",
  BIDIRECTIONAL_REFERENCE_CONFLICT = "BIDIRECTIONAL_REFERENCE_CONFLICT",
  INVALID_LEGACY_SHAPE = "INVALID_LEGACY_SHAPE"
}

export type ProjectMigrationError = {
  code: MigrationErrorCode;
  message: string;
  path?: string;
  sourceVersion?: string;
  roomId?: string;
  wallId?: string;
  levelId?: string;
  reason?: LegacyRoomBoundaryMigrationFailureReason;
};
